docker-compose-yaml: docker-compose.yml

project: typo3-example

tasks:
  post-rollout:
    - run:
        name: Lock backend
        command: vendor/bin/typo3 backend:lock
        service: cli
        shell: bash
    - run:
        name: Update DB
        command: |
          if [[ $(vendor/bin/typo3 configuration:showactive SYS/encryptionKey --json) != \"\" ]];
          then vendor/bin/typo3 database:updateschema "*" --verbose;
          else echo "no TYPO3 installed yet";
          fi
        service: cli
        shell: bash
    - run:
        name: Cache Flush
        command: |
          if [[ $(vendor/bin/typo3 configuration:showactive SYS/encryptionKey --json) != \"\" ]];
          then vendor/bin/typo3 cache:flush;
          else echo "no TYPO3 installed yet";
          fi
        service: cli
        shell: bash
    - run:
        name: Run pending upgrades
        command: |
          if [[ $(vendor/bin/typo3 configuration:showactive SYS/encryptionKey --json) != \"\" ]];
          then vendor/bin/typo3 upgrade:run;
          else echo "no TYPO3 installed yet";
          fi
        service: cli
        shell: bash
    - run:
        name: Warmup cache
        command: vendor/bin/typo3 cache:warmup
        service: cli
        shell: bash
    - run:
        name: Unlock backend
        command: vendor/bin/typo3 backend:unlock
        service: cli
        shell: bash

lagoon-sync:
  mariadb:
    config:
      hostname: "${MARIADB_HOST:-mariadb}"
      username: "${MARIADB_USERNAME:-lagoon}"
      password: "${MARIADB_PASSWORD:-lagoon}"
      port: "${MARIADB_PORT:-3306}"
      database: "${MARIADB_DATABASE:-lagoon}"
  files:
    config:
      sync-directory: "/app/public/fileadmin/user_upload"
